apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: abdulahad2242/mern-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb-service:27017/school_management"
            - name: PORT
              value: "5000"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
