name: Build and Deploy MERN School Management System
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mern-frontend
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mern-backend

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          CI=false
          npm install
          npm run build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: CI=false npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max

      - name: Set up Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Update Kubernetes Configs
        run: |
          sed -i "s|abdulahad2242/mern-frontend|${{ env.FRONTEND_IMAGE }}|g" frontend-deployment.yaml
          sed -i "s|abdulahad2242/mern-backend|${{ env.BACKEND_IMAGE }}|g" backend-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f mongodb-pvc.yaml
          kubectl apply -f mongodb-deployment.yaml
          kubectl apply -f mongodb-service.yaml
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f backend-service.yaml
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f frontend-service.yaml

      - name: Verify Deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/frontend-deployment
          kubectl wait --for=condition=available --timeout=300s deployment/backend-deployment
          kubectl wait --for=condition=available --timeout=300s deployment/mongodb-deployment

      - name: Get Service URLs
        run: |
          echo "Frontend URL: $(minikube service frontend-service --url)"
          echo "Backend URL: $(minikube service backend-service --url)"
